src/Edahira/DahiraBundle/Entity/Membres.php
<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Membres
 */
class Membres
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
	 * @Assert\Length(
     *      min = "2",
     *      minMessage = "Votre prénom doit faire au moins {{ limit }} caractères")
     */
    private $prenom;

    /**
     * @var string
	 * @Assert\Length(
     *      min = "2",
     *      minMessage = "Votre nom doit faire au moins {{ limit }} caractères")
     */
    private $nom;
    
    /**
     * @var boolean
     */
    private $sexe;

    /**
     * @var string
     */
    private $adresse;

    /**
     * @var string
	 * @Assert\Email(
     *     message = "'{{ value }}' n'est pas un email valide.",
     *     checkMX = false)
     */
    private $email;

    /**
     * @var string
     */
    private $telephone1;

    /**
     * @var string
	 */
    private $telephone2;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $dahiras;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $cotisations;

    /**
     * @var boolean
     */
    private $etat;

    /**
     * @var \Edahira\DahiraBundle\Entity\Categories
     */
    private $categorie;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $versements;

    /**
     * @var \Edahira\DahiraBundle\Entity\Dahira
     */
    private $dahira;

    /**
     * Constructor
     *
     * @param \Edahira\DahiraBundle\Entity\Dahira $dahira
     */
    public function __construct(\Edahira\DahiraBundle\Entity\Dahira $dahira)
    {
        $this->cotisations = new \Doctrine\Common\Collections\ArrayCollection();
        $this->dahiras = new \Doctrine\Common\Collections\ArrayCollection();
        $this->etat = true;
        $this->dahira = $dahira;
    }
   
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     * @return Membres
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string 
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Membres
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Get prenom nom
     *
     * @return string 
     */
    public function getAffichage()
    {
        return $this->prenom.' '.$this->nom;
    }

    /**
     * Set adresse
     *
     * @param string $adresse
     * @return Membres
     */
    public function setAdresse($adresse)
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * Get adresse
     *
     * @return string 
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Membres
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set telephone1
     *
     * @param string $telephone1
     * @return Membres
     */
    public function setTelephone1($telephone1)
    {
        $this->telephone1 = $telephone1;

        return $this;
    }

    /**
     * Get telephone1
     *
     * @return string 
     */
    public function getTelephone1()
    {
        return $this->telephone1;
    }

    /**
     * Set telephone2
     *
     * @param string $telephone2
     * @return Membres
     */
    public function setTelephone2($telephone2)
    {
        $this->telephone2 = $telephone2;

        return $this;
    }

    /**
     * Get telephone2
     *
     * @return string 
     */
    public function getTelephone2()
    {
        return $this->telephone2;
    }

    /**
     * Set etat
     *
     * @param boolean $etat
     * @return Membres
     */
    public function setEtat($etat)
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * Get etat
     *
     * @return boolean 
     */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * Add cotisations
     *
     * @param \Edahira\DahiraBundle\Entity\Cotisations $cotisations
     * @return Membres
     */
    public function addCotisation(\Edahira\DahiraBundle\Entity\Cotisations $cotisations)
    {
        $this->cotisations[] = $cotisations;

        return $this;
    }

    /**
     * Remove cotisations
     *
     * @param \Edahira\DahiraBundle\Entity\Cotisations $cotisations
     */
    public function removeCotisation(\Edahira\DahiraBundle\Entity\Cotisations $cotisations)
    {
        $this->cotisations->removeElement($cotisations);
    }

    /**
     * Get cotisations
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCotisations()
    {
        return $this->cotisations;
    }

    /**
     * Add dahiras
     *
     * @param \Edahira\DahiraBundle\Entity\Dahira $dahiras
     * @return Membres
     */
    public function addDahira(\Edahira\DahiraBundle\Entity\Dahira $dahiras)
    {
        $this->dahiras[] = $dahiras;

        return $this;
    }

    /**
     * Remove dahiras
     *
     * @param \Edahira\DahiraBundle\Entity\Dahira $dahiras
     */
    public function removeDahira(\Edahira\DahiraBundle\Entity\Dahira $dahiras)
    {
        $this->dahiras->removeElement($dahiras);
    }

    /**
     * Get dahiras
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getDahiras()
    {
        return $this->dahiras;
    }

    /**
     * Set dahiras
     *
     * @param \Edahira\DahiraBundle\Entity\Evenement $dahiras
     * @return Membres
     */
    public function setDahiras(\Edahira\DahiraBundle\Entity\Evenement $dahiras = null)
    {
        $this->dahiras = $dahiras;

        return $this;
    }


    /**
     * Set sexe
     *
     * @param boolean $sexe
     * @return Membres
     */
    public function setSexe($sexe)
    {
        $this->sexe = $sexe;

        return $this;
    }

    /**
     * Get sexe
     *
     * @return boolean 
     */
    public function getSexe()
    {
        return $this->sexe;
    }

    /**
     * Set categorie
     *
     * @param \Edahira\DahiraBundle\Entity\Categories $categorie
     * @return Membres
     */
    public function setCategorie(\Edahira\DahiraBundle\Entity\Categories $categorie = null)
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * Get categorie
     *
     * @return \Edahira\DahiraBundle\Entity\Categories 
     */
    public function getCategorie()
    {
        return $this->categorie;
    }

    /**
     * Add versements
     *
     * @param \Edahira\DahiraBundle\Entity\Versements $versements
     * @return Membres
     */
    public function addVersement(\Edahira\DahiraBundle\Entity\Versements $versements)
    {
        $this->versements[] = $versements;

        return $this;
    }

    /**
     * Remove versements
     *
     * @param \Edahira\DahiraBundle\Entity\Versements $versements
     */
    public function removeVersement(\Edahira\DahiraBundle\Entity\Versements $versements)
    {
        $this->versements->removeElement($versements);
    }

    /**
     * Get versements
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getVersements()
    {
        return $this->versements;
    }


    /**
     * Set dahira
     *
     * @param \Edahira\DahiraBundle\Entity\Dahira $dahira
     * @return Membres
     */
    public function setDahira(\Edahira\DahiraBundle\Entity\Dahira $dahira = null)
    {
        $this->dahira = $dahira;

        return $this;
    }

    /**
     * Get dahira
     *
     * @return \Edahira\DahiraBundle\Entity\Dahira 
     */
    public function getDahira()
    {
        return $this->dahira;
    }
}

src/Edahira/DahiraBundle/Form/ChargesType.php
<?php

namespace Edahira\DahiraBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Edahira\DahiraBundle\Form\MontantChargesType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Doctrine\ORM\EntityRepository;

class ChargesType extends AbstractType
{
    /**
     * @var integer
     *
     */
    protected $dahira;

    public function __construct($dahira){
        $this->dahira = $dahira;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $dahira = $this->dahira;
        $builder
            ->add('objet'   , 'text', array('label' => 'form.label.objet', 'translation_domain' => 'EdahiraDahiraBundle'))
            ->add('echeance', 'date', array('label' => 'form.label.echeance', 'translation_domain' => 'EdahiraDahiraBundle'))
            ->add('caisse'  , 'entity', array('label' => 'form.label.caisse', 'translation_domain' => 'EdahiraDahiraBundle',
                                              'class'    => 'EdahiraDahiraBundle:Caisses',
                                              'property' => 'nom',
                                              'multiple' => false,
                                              'expanded' => false,
                                              'query_builder' => function(EntityRepository $er) use ($dahira) {
                                                  return $er->getActivesCaisses($dahira);
                                            }))
            ->add('montants', 'collection', array('label' => 'form.label.montants', 'translation_domain' => 'EdahiraDahiraBundle',
                                                  'type' => new MontantChargesType($dahira)
                                                  ))
            ->add('etat'   , 'checkbox',array('required' => false, 'label' => 'form.label.etat', 'translation_domain' => 'EdahiraDahiraBundle'))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Edahira\DahiraBundle\Entity\Charges'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'edahira_dahirabundle_charges';
    }
}

src/Edahira/DahiraBundle/Controller/ChargesController.php
<?php

namespace Edahira\DahiraBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Edahira\DahiraBundle\Entity\Charges;
use Edahira\DahiraBundle\Entity\Categories;
use Edahira\DahiraBundle\Entity\MontantCharges;
use Edahira\DahiraBundle\Form\ChargesType;

class ChargesController extends Controller
{
	public function indexAction()
    {
    	$charges = $this->get('security.context')->getToken()->getUser()->getActiveDahira()->getCharges();
	    
		return $this->render('EdahiraDahiraBundle:Charges:index.html.twig', array(
		                     'charges'    => $charges
		));
    }

    public function editerAction(Charges $charge = null)
    {
    	$user = $this->get('security.context')->getToken()->getUser();

    	if(count($user->getActiveDahira()->getCaisses()) < 1){

            $url = $this->generateUrl("caisse_editer");
            $this->get('session')->getFlashBag()->add('info','action.caisse.create');
            return $this->render('EdahiraDahiraBundle:Charges:editer.html.twig');
        }
        elseif (count($user->getActiveDahira()->getCategories()) < 1) {

            $url = $this->generateUrl("categorie_editer");
            $this->get('session')->getFlashBag()->add('info','action.categorie.create');
            return $this->render('EdahiraDahiraBundle:Charges:editer.html.twig');
        }

        /*
         * Le bloc suivant permet d'assurer que les cotisationsde toutes les categories
         * du dahira sont ajoutées à la charge
         */
    	if(is_null($charge)){
			$charge = new Charges($user->getActiveDahira());
			
		}
		$cats = $catsVerif = array();
		foreach ($charge->getMontants() as $montantCh) {
			$catsVerif[] = $montantCh->getCategorie()->getId();
		}
		foreach ($user->getActiveDahira()->getCategories() as $categorie) {
			if(! in_array($categorie->getId(), $catsVerif)){
				$montantCharge = new MontantCharges();
				$montantCharge->setCategorie($categorie);
				$charge->addMontant($montantCharge);

			}
			$cats[] = $categorie->getId();
    	}
    	/*  fin de la verification */


    	$form = $this->createForm(new ChargesType($user->getActiveDahira()->getId()), $charge);


		$request = $this->get('request');

		if($request->getMethod() == 'POST'){
			$form->bind($request);
			$new = false;

			if($form->isValid()){
				$em = $this->getDoctrine()
				           ->getManager();
				if(is_null($charge->getId())){
					$new = true;

					$newId = $this->getDoctrine()
							       ->getManager()
				     		       ->getRepository('EdahiraDahiraBundle:Charges')
					    	       ->findLast()+1;

	                $charge->setId($newId);
	            }

				if($charge->getEcheance() < new \DateTime()){
					
					$this->get('session')->getFlashBag()->add('warning','flash.date.old');
					
					return $this->render('EdahiraDahiraBundle:Charges:editer.html.twig',array(
							'form'=>$form->createView(), 
							'charge'=> $charge
					));
				}

                foreach ($charge->getMontants() as $key => $montantCh) {
					$montantCh->setCharge($charge);
				}

				$em->persist($charge);
				if($new){
					$em->flush();
					$this->get('session')->getFlashBag()->add('success','flash.charge.added');
				}
				else{
					$em->flush();
					$this->get('session')->getFlashBag()->add('success','flash.charge.edited');
				}
				return $this->redirect($this->generateUrl('charges_index'));
			}
		}
		
		return $this->render('EdahiraDahiraBundle:Charges:editer.html.twig',array(
			'form'=>$form->createView(), 
			'charge'=> $charge
		));
    }

    public function changeretatAction(Charges $charge, $etat)
    {
    	$charge->setEtat($etat);

        $em = $this->getDoctrine()
		           ->getManager();
				 
		$em->persist($charge);
		$em->flush();
		if($etat)
		    $this->get('session')->getFlashBag()->add('success', 'flash.caisse.ferme');
	    else
	    	$this->get('session')->getFlashBag()->add('success', 'flash.caisse.ouvert');
		return $this->redirect( $this->generateUrl('charges_index'));
    }


    public function detailsAction(Charges $charge)
    {
    	$membres = $this->get('security.context')->getToken()->getUser()->getActiveDahira()->getMembres();
        
        return $this->render('EdahiraDahiraBundle:Charges:details.html.twig',array(
            'charge' => $charge,
            'membres' => $membres
        ));
    }

    public function supprimerAction(Charges $charge)
    {
        if($this->get('request')->getMethod() == 'POST'){

	    	$em = $this->getDoctrine()->getManager();
	    	foreach ($charge->getMontants() as $key => $montantCh) {
			    $em->remove($montantCh);
			}
			foreach ($charge->getVersements() as $key => $versement) {
			    $em->remove($versement);
			}

			$em->remove($charge);
			$em->flush();
			$this->get('session')->getFlashBag()->add('success', 'flash.charge.supprimer');
			
			return $this->redirect($this->generateUrl('charges_index'));
		}
    	return $this->render('EdahiraDahiraBundle:Charges:supprimer.html.twig', array('charge' => $charge));
    }
}

src/Edahira/DahiraBundle/Resources/views/Charges/details.html.twig
{% extends "EdahiraDahiraBundle::layout.html.twig" %}

{% trans_default_domain 'EdahiraDahiraBundle' %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        #edahira_dahirabundle_dons_date select{
            width:73px
        }
    </style>
{% endblock %}

{% block title %}{{ parent()}} | {{'label.charge' | lower | trans }}{% endblock %}

{% block body_header %}
	<h1>{{ 'text.versement' | trans({'%objet%': 'charge'}) }}  <small>{{ charge.objet }}</small></h1>
{% endblock %}

{% block body_content%}
	{{ parent() }}


	<b>{{ 'label.totalverse' | trans }}: {{ getSoldeCharge(charge) }}</b> FCFA
	<br/>
	<br/>

	{% if membres | length > 0 %}
		<table class="table table-striped table-bordered table-condensed">
			<thead>
				<tr>
					<th>{{ 'label.membre'| trans }}</th>
					<th>{{ 'label.categorie'| trans }}</th>
					<th>{{ 'label.montantverse'| trans }}</th>
					<th>{{ 'label.restant'| trans }}</th>
				</tr>
			</thead>
			<tbody>
			{% for membre in membres %}
				<tr class="list-users">
					<td>{{ membre.affichage }}</td>
					<td>{{ membre.categorie.nom }} ({{getMontantCharge(charge, membre.categorie)}})</td>
					<td>{{ getBalanceMembre(charge, membre) }}</td>
					<td>{{ getMontantCharge(charge, membre.categorie) - getBalanceMembre(charge, membre) }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		<br/>
		<span class="alert alert-info"><a href="{{path('etats_chargemembre')}}" title=""> {{'label.voirdetailparmembre' | trans }}</a></span>
	{% else %}
		<p>{{ 'text.aucun' | trans({'%objet%': 'membre'}) }}</p>
	{% endif %}

	<div class="page-header">
        <h1><small>{{ 'label.dons' | trans }}</small></h1>
    </div>
    <div id="dons_id" >
        {{ render(controller('EdahiraDahiraBundle:Don:index', {'type': 2, 'idType': charge.id})) }}
        
        <a id="ajouter_don" href="" class="btn btn-success">{{ 'label.ajouter' | trans }}</a>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $("#ajouter_don").click(function(e){
            /* e.preventDefault(); */
            /* var DATA = $(this).serialize(); */
            $.ajax({
                type: "GET",
                url: "{{ path('don_editer', {'idType': charge.id, 'type': 2, 'id': null})}}",
             /* data: DATA,*/
                cache: false,
                success: function(data){
                   $('#dons_id').html(data);
                }
            });    
            return false;
        });
        function editDon(don){
            /* alert(link); */
            $.ajax({
                type: "GET",
                url: don,
                cache: false,
                success: function(data){
                   $('#dons_id').html(data);
                }
            });    
            return false;
        }
    </script>
{% endblock %}

src/Edahira/DahiraBundle/Resources/views/Charges/editer.html.twig
{% extends "EdahiraDahiraBundle::layout.html.twig" %}

{% trans_default_domain 'EdahiraDahiraBundle' %}

{% block stylesheets %}
	{{ parent() }}
	<style>
		#edahira_dahirabundle_charges_echeance select{
		    width:73px
		}
	</style>
{% endblock %}

{% block title %}{{ parent()}} | {{'label.charge' | lower | trans }}{% endblock %}

{% block body_header %}
	
	{% if charge.id is defined %}
		<h1>{{ 'text.modification' | trans({'%objet%': 'charge'}) }}</h1>
	{% else %}
		<h1>{{ 'text.nouvelle' | trans({'%objet%': 'charge'}) }}</h1>
	{% endif %}

{% endblock %}

{% block body_content%}
	{{ parent() }}

	{% if form is defined %}
		{% include "EdahiraDahiraBundle:Charges:formCharges.html.twig" %}
	{% endif %}
{% endblock %}

src/Edahira/DahiraBundle/Resources/views/Charges/formCharges.html.twig
{% trans_default_domain 'EdahiraDahiraBundle' %}

<form class="form-horizontal" action="{{ path('charges_editer',{'id': charge.id}) }}" method="post" {{ form_enctype(form) }}>
	{{ form_errors(form) }}
	<fieldset>
		<div class="control-group">
			<label class="control-label" for="">{{ form_label(form.objet) }}</label>
			<div class="controls">
				{{ form_widget(form.objet) }}
				{{ form_errors(form.objet) }}
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="">{{ form_label(form.echeance) }}</label>
			<div class="controls">
				{{ form_widget(form.echeance) }}
				{{ form_errors(form.echeance) }}
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="">{{ form_label(form.caisse) }}</label>
			<div class="controls">
				{{ form_widget(form.caisse) }}
				{{ form_errors(form.caisse) }}
			</div>
		</div>

		{% for montant in form.montants %}
		<div class="control-group">
			<label class="control-label" for="">{{ form_label(form.montants) }}</label>
			<div class="controls">
				{{ form_widget(montant.categorie) }}
				{{ form_errors(montant.categorie) }}
				{{ form_widget(montant.montant) }}
				{{ form_errors(montant.montant) }}
			</div>
		</div>
		{% endfor %}

		<div class="control-group">
			<label class="control-label" for="">{{ form_label(form.etat) }}</label>
			<div class="controls">
				{{ form_widget(form.etat) }}
				{{ form_errors(form.etat) }}
			</div>
		</div>


		{{ form_rest(form) }} 

        <div class="form-actions">
			<input type="submit" class="btn btn-success btn-large" value={{ 'label.enregistrer'| trans}} />
			<a class="btn" href="{{ path(app.session.get('last_route'), {'id':charge.id} )}}">{{ 'label.annuler'| trans}}</a>
		</div>
	</fieldset>
</form>

src/Edahira/DahiraBundle/Resources/views/Charges/index.html.twig
{% extends "EdahiraDahiraBundle::layout.html.twig" %}

{% trans_default_domain 'EdahiraDahiraBundle' %}

{% block title %}{{ parent() }} | {{ 'label.charges' | trans }} {% endblock %}

{% block body_header %}
	<h1>{{ 'text.list' | trans({'%objet%': 'charges'}) }}</h1>
{% endblock %}

{% block body_content %}
	{{ parent() }}
	
	{% if charges | length > 0 %}
		<table class="table table-striped table-bordered table-condensed">
			<thead>
				<tr>
					<th>{{ 'label.nom'| trans }}</th>
					<th>{{ 'label.echeance'| trans }}</th>
					<th>{{ 'label.caisse'| trans }}</th>
					<th>{{ 'label.etat'| trans }}</th>
					<th>{{ 'label.actions'| trans }}</th>
				</tr>
			</thead>
			<tbody>
			{% for charge in charges %}
				<tr class="list-users">
					<td>{{ charge.objet }}</td>
					<td>{{ charge.echeance | date('d-m-Y') }}</td>
					<td>{{ charge.caisse.nom }}</td>
					{% if charge.etat == true %}
						<td><span class="label label-success">{{ 'label.ouvert' | trans}}</span></td>
					{% else %}
						<td><span class="label label-important">{{ 'label.ferme' | trans}}</span></td>
					{% endif %}
					<td>
						<div class="btn-group">
							<a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">{{ 'label.actions'| trans }} <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="{{ path('charges_details', {'id': charge.id}) }}"><i class="icon-align-left"></i> {{ 'action.detailsversement' |trans }}</a></li>
								<li><a href="{{ path('charges_editer', {'id': charge.id}) }}"><i class="icon-pencil"></i> {{ 'action.edit' |trans }}</a></li>
								<li><a href="{{ path('charges_supprimer', {'id': charge.id}) }}"><i class="icon-trash"></i> {{ 'action.delete' |trans }}</a></li>
                            {% if charge.etat == true %}
								<li><a href="{{ path('charges_changeretat', {'id': charge.id, etat: 0}) }}"><i class="icon-folder-close"></i> {{ 'label.fermer' | trans}}</a></li>
							{% else %}
							    <li><a href="{{ path('charges_changeretat', {'id': charge.id, etat: 1}) }}"><i class="icon-folder-open"></i> {{ 'label.ouvrir' | trans}}</a></li>
							{% endif %}
							</ul>
						</div>
					</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		{% else %}
			<p>{{ 'text.fem.aucun' | trans({'%objet%': 'charge'}) }}</p>
		{% endif %}
	<a href="{{ path('charges_editer') }}" class="btn btn-success">{{ 'label.ajouter' | trans }}</a>

{% endblock %}

src/Edahira/DahiraBundle/Resources/views/Charges/supprimer.html.twig
{% extends "EdahiraDahiraBundle::layout.html.twig" %}

{% trans_default_domain 'EdahiraDahiraBundle' %}

{% block title %}{{ parent()}} | {{'label.charge' | lower | trans }}{% endblock %}

{% block body_header %}
	<h1>{{ 'text.fem.suppression' | trans({'%objet%': 'charge: '~charge.objet}) }}</h1>
{% endblock %}

{% block body_content %}
	{{ parent() }}
	<form class="form-horizontal" action="{{ path('charges_supprimer',{'id': charge.id}) }}" method="post" >
		<fieldset>
	        <div class="form-actions">
				<input type="submit" class="btn btn-success btn-large" value={{ 'label.supprimer'| trans}} />
				<a class="btn" href="{{ path('charges_index') }}">{{ 'label.annuler'| trans}}</a>
			</div>
		</fieldset>
	</form>
{% endblock %}